### ISSUE TITLE
armv7 issue

### ISSUE THREAD

**Issue by maksTheAwesome** [abellono/IssueReporter#5]
Installed the component with cocoa pods. Added #import <IssueReporter/ABEReporter.h> to AppDelegate 
But the line:
[ABEReporter setupWithRepositoryName:@"name/Project" gitHubAccessToken:@"token" imgurClientID:@"id"];

Causes the following compiler error:

_OBJC_CLASS_$_ABEReporter", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture armv7

Can you advise where to find the problem?

**Comment by hhanesand** [comment]
Can you include your podfile? If you have `use_frameworks!` in there, then use `@import IssueReporter`.

**Comment by maksTheAwesome** [comment]
Adding use_frameworks! worked perfectly. I thought it for swift projects. Thank you.
